package com.example.delivery.client;

import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.GetMapping;

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import io.github.resilience4j.retry.annotation.Retry;

@FeignClient(name="user-service")
public interface UserClient {
	
	@GetMapping("/user/test")
	@Retry("userCB")
	@CircuitBreaker(name="userCB", fallbackMethod="getUserFallback")
	public String testValue();
	
	default String getUserFallback(Throwable exception) {
		System.out.println("Exception class=" + exception.getClass().getName());
		System.out.println("Exception took place: " + exception.getMessage());
		return "something happen";
	}
}
